#Lists associated with the bot

playing=["With Yofi",
         "Skyrim",
         "Bioshock",
         "Not Fortnite bc fuck that shit",
         #"Time is a relative concept",
         "Meeting hot milfs in my area",
         "cards with my personal friend Bradley Cooper",
         #"Air Guitar Violently",
         #"A little game I like to call how many dicks can fit in my ass",
         "Valorant? Lmao Nah",
         "With my prisoners",
         "Hi Toby!!",
         "minecraft ig?",
         "Don't do drugs kids",
         "Stay in drugs. Don't do school!",
         "Hypixel>Mineplex",
         "Do you like the bot?",
         "There's chemicals in the water that turn the fricken frogs gay!",
         "I never meant to give you mushrooms girl",
         "Ah shit, here we go again",
         "me like a dummy like bitch are you dumb",
         "dat one x song that go woo",
         "Remember Villager News?",
         "ZA WARUDO",
         "WAAAAAAAAA",
         "Hi kids, do you like violence?",
         "Keanuwu *nuzzles you*",
         "But like, did you see the dog?",
         "2 EZ 4 MAG 7!!!",
         "LESS EZ 4 XM!!!",
         "What's the difference between a baby and a football?",
         "Inertia is a property of matter",
         '"The fifth president was Lincoln, right?" ~Maggie Skyler Moo Deutsch',
         "Bababooey",
         "It's not gay if you have socks on",
         "WEAR A MASK!!!!",
         "Say my name",
         "and knuckles",
         "ONE OF US ONE OF US",
         "Wanna be a member, wanna be a member?",
         "Bats are not scary, bats are tiny mammals",
         "Beep boop I am a bot",
         "Annie, please come back. I've changed",
         "Awping is just scout on EZ mode",
         "Thanks Ugly God",
         "I made my family disappear",
         "I'm standing here with poison in my pocket",
         "Sub to Technoblade",
         "AWOOGA AWOOGA! HOT MAMA NOW THATS A DAME!!",
         "Ay yo, fuck cancer",
         "I am the danger",
         "Yeah science!!",
         "Using quantum mechanics to prove traps aren't gay",
         "Dick Cheney made money off the Iraq war",
         "Kersplash is the best sound",
         "Gordon Freeman, in the flesh",
         "No regrets Mr. Freeman",
         "Duck Favid",
         "Ducking is a real word, not a typo",
         "Cheese with a z",
         "Cheeze",
         "Bing Bong",
         "My home town of New York City",
         "Do you know the definition of insanity?",
         "A man chooses. A slave obeys",
         "SUPERHOT is the most innovative shooter I've played in years!",
         "Ninke Minjaj",
         "Back in the 90s, I was in a very famous TV show",
         "Back in 07, I was in an unsuccessful TV show",
         "Lawnmower? I hardly know her!",
         "Do you wanna know how I got these scars?",
         "Would you kindly?",
         "spujb",
         "Sneakey beakey like",
         "We're not taking a windy walk here",
         "First we kill them, and then we go home",
         "Only in zoo york",
         "Uhh, meow?",
         "War. War never changes",
         "I still have no closer",
         "SPREAD",
         "Dude, git lowkey sucks",
         "This is my partner, Sh'Dynasty",
         "Suck it soup",
         "CSGO>R6S"]

##minion=["https://i.ytimg.com/vi/JNmeVsBp8X4/maxresdefault.jpg",
##        "https://i.redd.it/l8lumq449cu21.png",
##        "https://cosbymemes.com/wp-content/uploads/2019/12/Top-25-New-Minion-Memes-1-1024x931.jpeg",
##        "https://pbs.twimg.com/media/EBO_a8AX4AEFNL1.jpg",
##        "https://i.redd.it/812oi54pgvuy.jpg",
##        "https://i.insider.com/5955728816160fa6018b485c?width=1100&format=jpeg&auto=webp",
##        "https://cosbymemes.com/wp-content/uploads/2019/12/Top-25-New-Minion-Memes-1-1024x812.jpg"]

prof=["https://ibb.co/g7cN19C",
      "https://ibb.co/NWwMSgj",
      "https://ibb.co/5LRsT4M",
      "https://ibb.co/wg4JrpW",
      "https://ibb.co/QJKYfgY",
      "https://ibb.co/GtwVxHY",
      "https://ibb.co/jf9M6ck",
      "https://ibb.co/2d75mNM",
      "https://ibb.co/3kKw9mj",
      "https://ibb.co/WzxQBnN"]

ilan=["Ilan liked Miriam?",
      "Ilan cried over Miriam?",
      "Ilan liked Shira?",
      "Ilan's mom thought he was gay?",
      "Ilan lost a fight to me before I started working out?",
      "Ilan thought I gave a fuck about his opinion?",
      "Ilan tried to get me privacy striked?"]

swears=["fuck",
        "shit",
        "ass",
        "bitch",
        "cunt"]

    
die=["Goodbye Cruel World!!",
     "I blame you for this.",
     "I can see the black mountain!",
     "Oh it hurts, it hurts!!",
     "WHYYYYYYYYYYYYYYYYYY",
     "Dust to dust",
     "Reality is an Illusion, the universe is a hologram, buy gold. BYEEEEEEEEEEEE",
     "Bomb has been planted",
     "Rosebud",
     "Strike me down and I'll become more powerful than you can ever imagine."]
