#Lists associated with the bot

playing=["With Fire",
         "Skyrim",
         "Bioshock",
         "Not Fortnite bc fuck that shit",
         "Meeting hot milfs in my area",
         "Valorant? Lmao Nah",
         "With my prisoners",
         "Hi Toby!!",
         "minecraft ig?",
         "Don't do drugs kids",
         "Stay in drugs. Don't do school!",
         "Hypixel>Mineplex",
         "Do you like the bot?",
         "There's chemicals in the water that turn the fricken frogs gay!",
         "I never meant to give you mushrooms girl",
         "Ah shit, here we go again",
         "me like a dummy like bitch are you dumb",
         "dat one x song that go woo",
         "Remember Villager News?",
         "ZA WARUDO",
         "Hi kids, do you like violence?",
         "Keanuwu *nuzzles you*",
         "But like, did you see the dog?",
         "2 EZ 4 MAG 7!!!",
         "LESS EZ 4 XM!!!",
         "What's the difference between a baby and a football?",
         "Inertia is a property of matter",
         '"The fifth president was Lincoln, right?" ~Maggie Skyler Moo Deutsch',
         "Bababooey",
         "It's not gay if you have socks on",
         "WEAR A MASK!!!!",
         "Say my name",
         "and knuckles",
         "ONE OF US ONE OF US",
         "Wanna be a member, wanna be a member?",
         "Bats are not scary, bats are tiny mammals",
         "Beep boop I am a bot",
         "Annie, please come back. I've changed",
         "AWPing is just scout on EZ mode",
         "Thanks Ugly God",
         "I made my family disappear",
         "I'm standing here with poison in my pocket",
         "Sub to Technoblade",
         "AWOOGA AWOOGA! HOT MAMA NOW THATS A DAME!!",
         "Ay yo, fuck cancer",
         "I am the danger",
         "Yeah science!!",
         "Using quantum mechanics to prove traps aren't gay",
         "Dick Cheney made money off the Iraq war",
         "Kersplash is the best sound",
         "Gordon Freeman, in the flesh",
         "No regrets Mr. Freeman",
         "Duck Favid",
         "Ducking is a real word, not a typo",
         "Cheese with a z",
         "Cheeze",
         "Bing Bong",
         "My home town of New York City",
         "Do you know the definition of insanity?",
         "A man chooses. A slave obeys",
         "SUPERHOT is the most innovative shooter I've played in years!",
         "Ninke Minjaj",
         "Back in the 90s, I was in a very famous TV show",
         "Back in 07, I was in an unsuccessful TV show",
         "Lawnmower? I hardly know her!",
         "Do you wanna know how I got these scars?",
         "Would you kindly?",
         "spujb",
         "Sneakey beakey like",
         "We're not taking a windy walk here",
         "First we kill them, and then we go home",
         "Only in zoo york",
         "Uhh, meow?",
         "War. War never changes",
         "I still have no closer",
         "𝓢𝓟𝓡𝓔𝓐𝓓",
         "Dude, git lowkey sucks",
         "This is my partner, Sh'Dynasty",
         "Suck it soup",
         "CSGO>R6",
         "In Technicolor",
         "Hey Lois. UNGA BUNGA LOIS",
         "Sub to SomeOrdinary Gamers",
         "@jewfacebaby wm?",
         "¿¿¿uʍop ʇǝƃ I op ʍoɥ 'ʇᴉɥs ʇᴉɐʍ",
         "uᴉɐƃɐ ʇou ʇᴉɥs ɥO"]


prof=["https://ibb.co/g7cN19C",
      "https://ibb.co/NWwMSgj",
      "https://ibb.co/5LRsT4M",
      "https://ibb.co/wg4JrpW",
      "https://ibb.co/QJKYfgY",
      "https://ibb.co/GtwVxHY",
      "https://ibb.co/jf9M6ck",
      "https://ibb.co/2d75mNM",
      "https://ibb.co/3kKw9mj",
      "https://ibb.co/WzxQBnN"]

ilan=["Ilan liked Miriam?",
      "Ilan cried over Miriam?",
      "Ilan liked Shira?",
      "Ilan got dumped by Shira?",
      "Ilan's mom thought he was gay?",
      "Ilan lost a fight to me",
      "Ilan thought I gave a fuck about his opinion?",
      "Ilan tried to get me privacy striked?",
      "this website existed?\nhttps://www.henrybenamram.com",
      "Ilan made skywars with wolfZDA?",
      "Ilan was a confirmed member of the taliban?",
      "Ilan had sex with a pig on live televison?",
      "Ilan killed Princess Diana?",
      "Ilan directly caused the armenian genocide"]

swears=["fuck",
        "shit",
        "ass",
        "bitch",
        "cunt"]

    
die=["Goodbye Cruel World!!",
     "I blame you for this.",
     "I can see the black mountain!",
     "Oh it hurts, it hurts!!",
     "WHYYYYYYYYYYYYYYYYYY",
     "Dust to dust",
     "Reality is an Illusion, the universe is a hologram, buy gold. BYEEEEEEEEEEEE",
     "Bomb has been planted",
     "Rosebud",
     "Strike me down and I'll become more powerful than you can ever imagine."]
